services:
  oracle-db:
    image: container-registry.oracle.com/database/free:23.5.0.0
    container_name: oracle-db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=password
      - ORACLE_CHARACTERSET=AL32UTF8
    volumes:
      # Ensure your ./data directory has sufficient permissions and space on your host
      - ./data:/opt/oracle/oradata
    networks:
      - oracle-net
    restart: unless-stopped

networks:
  oracle-net:
    driver: bridge